NAME        = clock
EXTRA_DEPS  = ../../forth/lib/vdg.fs \
              ../../forth/lib/screen.fs \
              ../../forth/lib/rg-pixel.fs \
              ../../forth/lib/datawrite.fs \
              ../../forth/lib/font-art.fs \
              ../../forth/lib/trig.fs \
              ../../forth/lib/fujinet.fs
XROAR_EXTRA = -cart-rom ~/.xroar/roms/hdbdw3cc2.rom -cart-autorun -kbd-translate

include ../../make/demo.mk
